### ISSUE TITLE
Compatibility with 8.2 build (201610071157)

### ISSUE THREAD

**Issue by 358b06c6** [mirkobrombin/Atom-Netbeans-Theme#2]
Does not work with the latest version of Netbeans.

**Comment by mirkobrombin** [comment]
Solved, download the new release from Netbeans plugins page or [Here](https://github.com/mirkobrombin/Atom-Netbeans-Theme/releases).

**Comment by 358b06c6** [comment]
¡Hello, mirkobrombin!

**Download the release of your theme and I get this:**

![message](https://user-images.githubusercontent.com/26587524/28241320-02dfeb46-6958-11e7-8fb8-ea4e7c63487e.png)

**My version of NetBeans:** NetBeans IDE 8.2 (Build 201610071157)

**Comment by mirkobrombin** [comment]
Are you importing using the correct form?
